---
- hosts: localhost
  connection: local
  tasks:
  
    - name: Enabled RPM Fusion Free Repo
      become: true
      yum: 
        name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-rawhide.noarch.rpm

    - name: Enabled RPM Fusion Non-Free Repo
      become: true
      yum:
        name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-rawhide.noarch.rpm
      
    - name: Enabled Alacritty Copr Repo
      become: true
      command:
        cmd: dnf copr enable -y pschyska/alacritty
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:pschyska:alacritty.repo
      
    - name: Enabled Minikube Copr Repo
      become: true
      command:
        cmd: dnf copr enable -y dvdmuckle/minikube-rpm
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:dvdmuckle:minikube-rpm.repo
      
    - name: Enabled Discord Copr Repo
      become: true
      command:
        cmd: dnf copr enable -y duskmourn/discord
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:duskmourn:discord.repo
      
    - name: Enabled Universal Ctags Copr Repo
      become: true
      command:
        cmd: dnf copr enable -y jgoguen/universal-ctags
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:jgoguen:universal-ctags.repo
      
    - name: Enabled CRI-O Module
      become: true
      command:
        cmd: dnf module enable cri-o:1.18

    - name: Has configured SwayWM 
      become: true
      package:
        name: "{{ item }}"
      with_items:
        - sway
        - rofi
        - xclip

    - name: Has firefox
      become: true
      package:
        name: "{{ item }}"
      with_items:
        - firefox
        - ffmpeg-libs

    - name: Has console tools 
      become: true
      package:
        name: "{{ item }}"
      with_items:
        - alacritty
        - zsh
        - fzf
        - git
        - feh
        - exa
        - atool
        - ripgrep
        - bat
        - cri-o

    - name: Has dev tools 
      become: true
      package:
        name: "{{ item }}"
      with_items:
        - kubernetes-client
        - nodejs
        - maven
        - java-11-openjdk
        - universal-ctags
        - java-11-openjdk-devel
        - minikube
        - cri-o
        - httpie
  
    - name: Has chezmoi
      become: true
      yum: 
        name: https://github.com/twpayne/chezmoi/releases/download/v1.8.7/chezmoi-1.8.7-x86_64.rpm
        disable_gpg_check: true
        
    - name: Upgrade all packages
      become: true
      yum:
        name: '*'
        state: latest

    - name: Set timezone to Europe/Moscow
      become: true
      community.general.timezone:
        name: Europe/Moscow

    - name: Has python packages
      pip:
        name: neovim
