---
- hosts: localhost
  connection: local
  tasks:
  
    - name: Enabled RPM Fusion Free Repo
      become: true
      yum: 
        disable_gpg_check: yes
        name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-34.noarch.rpm

    - name: Enabled RPM Fusion Non-Free Repo
      become: true
      yum:
        disable_gpg_check: yes
        name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-34.noarch.rpm
      
    - name: Enabled Alacritty Copr Repo
      become: true
      command:
        cmd: dnf copr enable -y pschyska/alacritty
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:pschyska:alacritty.repo
      
    - name: Enabled Neovim Copr Repo
      become: true
      command:
        cmd: dnf copr enable -y agriffis/neovim-nightly
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:agriffis:neovim-nightly.repo
      
    - name: Enabled Blanket Copr Repo
      become: true
      command:
        cmd: dnf copr enable -y tuxino/blanket
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:tuxino:blanket.repo
      
    - name: Enabled Minikube Copr Repo
      become: true
      command:
        cmd: dnf copr enable -y johan/fedora-rpms
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:johan:fedora-rpms.repo
      
    - name: Enabled Discord Copr Repo
      become: true
      command:
        cmd: dnf copr enable -y dvdmuckle/discord
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:duskmourn:discord.repo
      
    - name: Enabled Alebastr Sway Repo
      become: true
      command:
        cmd: dnf copr enable -y alebastr/sway-extras
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:alebastr:sway-extras.repo

    - name: Enabled Universal Ctags Copr Repo
      become: true
      command:
        cmd: dnf copr enable -y jgoguen/universal-ctags
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:jgoguen:universal-ctags.repo
      
    - name: Enabled CRI-O Module
      become: true
      command:
        cmd: dnf module enable -y cri-o:1.20

    - name: Has configured SwayWM 
      become: true
      package:
        name: "{{ item }}"
      with_items:
        - sway
        - rofi
        - xclip
        - wl-clipboard
        - nwg-launchers
        - greetd
        - greetd-gtkgreet
        - swaylock
        - dnf-automatic
        - podman

    - name: Has enabled greetd SystemD Service
      become: true
      ignore_errors: true
      systemd:
        name: greetd
        enabled: yes

    - name: Has browser
      become: true
      package:
        name: "{{ item }}"
      with_items:
        - firefox
        - ffmpeg-libs
        - qutebrowser
        - qt5-qtwebengine-freeworld

    - name: Has console tools 
      become: true
      package:
        name: "{{ item }}"
      with_items:
        - alacritty
        - zsh
        - fzf
        - git
        - feh
        - exa
        - atool
        - ripgrep
        - bat

    - name: Has dev tools 
      become: true
      package:
        name: "{{ item }}"
      with_items:
        - kubernetes-client
        - nodejs
        - maven
        - java-11-openjdk
        - universal-ctags
        - java-11-openjdk-devel
        - minikube
        - cri-o
        - httpie
        - neovim

    - name: Has some packages
      become: true
      package:
        name: "{{ item }}"
      with_items:
        - blanket
        - Discord-installer
        - evince
  
    - name: Has chezmoi
      become: true
      yum: 
        name: https://github.com/twpayne/chezmoi/releases/download/v1.8.7/chezmoi-1.8.7-x86_64.rpm
        disable_gpg_check: true
      
    - name: Chezmoi inited
      become: false
      command:
        cmd: chezmoi init https://github.com/stCarolas/dotfiles.git --apply

    - name: Create a directory if it does not exist
      file:
        path: "~/.ssh"
        state: directory
        mode: '0755'

    - name: generate SSH key
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        force: no
        
    - name: Upgrade all packages
      become: true
      yum:
        name: '*'
        state: latest

    - name: Set timezone to Europe/Moscow
      become: true
      community.general.timezone:
        name: Europe/Moscow

    - name: Has python packages
      pip:
        name: neovim
