---
- hosts: localhost
  connection: local
  tasks:

    - name: Set timezone to Europe/Moscow
      become: true
      community.general.timezone:
        name: Europe/Moscow

    - name: Has required directories created
      import_tasks: "./tasks/directories.yml"

    - name: Has RPM Fusion enabled
      import_tasks: "./tasks/rpmfusion.yml"
      tags: rpmfusion

    - name: Has chezmoi installed and configs inited
      import_tasks: "./tasks/chezmoi.yml"
      tags: chezmoi

    - name: Has sway and correlated tools installed
      import_tasks: "./tasks/sway.yml"
      tags: sway

    - name: Has browser installed
      import_tasks: "./tasks/browsers.yml"
      tags: browsers

    - import_tasks: "./tasks/term.yml"
      tags: term

    - name: Has development tools installed
      import_tasks: "./tasks/devtools.yml"
      tags: devtools

    - name: Has neovim with dependencies installed
      import_tasks: "./tasks/neovim.yml"
      tags: neovim

    - name: Has apps installed
      import_tasks: "./tasks/apps.yml"
      tags: apps

    - name: Has ssh key generated
      import_tasks: "./tasks/sshkey.yml"
