---
- hosts: localhost
  connection: local
  tasks:

    - name: Set timezone to Europe/Moscow
      become: true
      community.general.timezone:
        name: Europe/Moscow

    - include_tasks: "./tasks/rpmfusion.yml"
    - include_tasks: "./tasks/sway.yml"
    - include_tasks: "./tasks/browsers.yml"
    - include_tasks: "./tasks/term.yml"
    - include_tasks: "./tasks/neovim.yml"
    - include_tasks: "./tasks/java.yml"
    - include_tasks: "./tasks/apps.yml"
    - include_tasks: "./tasks/sshkey.yml"

    - name: Upgrade all packages
      become: true
      yum:
        name: '*'
        state: latest
