- name: Flatpak is installed
  become: true
  package:
    name: flatpak

- name: Use Flathub as a repo
  become: true
  command:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Evince is installed
  become: true
  package:
    name: evince

- name: pavucontrol is installed
  become: true
  package:
    name: pavucontrol

- name : Discord is installed
  become: true
  flatpak:
    name: com.discordapp.Discord

- name: Has openvpn is installed
  become: true
  package:
    name: openvpn
