- name: Use Flathub as a repo
  become: true
  command:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Evince installed
  become: true
  package:
    name: evince

- name: pavucontrol installed
  become: true
  package:
    name: pavucontrol

- name : Discord installed
  flatpak:
    name: com.discordapp.Discord

- name : Mailspring installed
  flatpak:
    name: com.getmailspring.Mailspring
