# vi: ft=yaml.ansible

- name: Flatpak is installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: flatpak

- name: Use Flathub as a repo
  tags: [system]
  become: true
  community.general.flatpak_remote:
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    name: flathub

- name: Evince is installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: evince

- name: Has pavucontrol installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: pavucontrol

- name: Discord is installed
  become: true
  community.general.flatpak:
    name: com.discordapp.Discord

- name: Has openvpn is installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: openvpn

- name: Has waydroid installed
  become: true
  ansible.builtin.package:
    name: waydroid
