- name: Has chezmoi repos
  become: true
  yum: 
    disable_gpg_check: yes
    name: https://github.com/twpayne/chezmoi/releases/download/v1.8.7/chezmoi-1.8.7-x86_64.rpm
      
- name: Chezmoi inited
  become: false
  command:
    cmd: chezmoi init https://github.com/stCarolas/dotfiles.git --apply
