- name: Has chezmoi repos
  become: true
  yum:
    disable_gpg_check: yes
    name: https://github.com/twpayne/chezmoi/releases/download/v2.43.0/chezmoi-2.43.0-x86_64.rpm

- name: Chezmoi inited
  become: false
  command:
    cmd: chezmoi init https://github.com/stCarolas/dotfiles.git --apply
