# vi: ft=yaml.ansible

- name: Has chezmoi repos
  become: true
  ansible.builtin.yum:
    disable_gpg_check: true
    name: https://github.com/twpayne/chezmoi/releases/download/v2.43.0/chezmoi-2.43.0-x86_64.rpm

- name: Chezmoi inited
  become: false
  ansible.builtin.command:
    cmd: chezmoi init https://github.com/stCarolas/dotfiles.git --apply
