# vi: ft=yaml.ansible

- name: Has java packages installed
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - maven
    - java-17-openjdk
    - java-17-openjdk-devel
    - java-latest-openjdk
    - java-latest-openjdk-devel

- name: Has luarocks installed
  become: true
  ansible.builtin.package:
    name: luarocks

- name: Has pip installed
  become: true
  ansible.builtin.package:
    name: python3-pip

- name: Has node.js and npm installed
  become: true
  ansible.builtin.package:
    name: nodejs

- name: Has Vagrant
  become: true
  ansible.builtin.package:
    name: vagrant

- name: Has k8s tools
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - kubernetes-client
    - helm

- name: Has podman-compose installed
  become: true
  ansible.builtin.package:
    name: podman-compose

- name: Has Cargo
  become: true
  ansible.builtin.package:
    name: cargo
