# vi: ft=yaml.ansible

- name: Has java packages installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - maven
    - java-latest-openjdk
    - java-latest-openjdk-devel

- name: Has luarocks installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: luarocks

- name: Has cargo installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: cargo

- name: Has yarn installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: yarnpkg

- name: Has pip installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: python3-pip

- name: Has node.js and npm installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: nodejs

- name: Has k8s tools
  tags: [system]
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - kubernetes-client
