# vi: ft=yaml.ansible

- name: Certain directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "~/Coding"
    - "~/Coding/projects"
    - "~/Coding/libs"
    - "~/Pictures"
    - "~/Pictures/Wallpapers"
    - "~/Pictures/Screenshots"

- name: Delete unnecessary folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "~/Documents"
    - "~/Music"
    - "~/Templates"
    - "~/Videos"
    - "~/Public"
    - "~/Desktop"
