- name: Exists certain directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "~/Coding"
    - "~/Coding/projects"
    - "~/Pictures"
    - "~/Pictures/Wallpapers"
    - "~/Pictures/Screenshots"

- name: Delete unnecessary folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "~/Documents"
    - "~/Music"
    - "~/Templates"
    - "~/Videos"
    - "~/Public"
    - "~/Desktop"
