# vi: ft=yaml.ansible

- name: Has neovim-nightly repos
  tags: [system]
  become: true
  ansible.builtin.command:
    cmd: dnf copr enable -y agriffis/neovim-nightly
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:agriffis:neovim-nightly.repo

- name: Has common system tools
  tags: [system]
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - tar
    - unzip

- name: Has neovim packages installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - neovim
    - glibc-static # needed for treesitter
    - libstdc++-static # needed for treesitter
    - gcc-c++ # needed for treesitter

- name: Has neovim python package installed
  tags: [system]
  ansible.builtin.pip:
    name: neovim

- name: Has sqlite packages installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - sqlite
    - sqlite-devel
    - sqlite-tcl

- name: Has prettier installed
  tags: [system]
  become: true
  community.general.npm:
    global: true
    name: "{{ item }}"
  with_items:
    - prettier
    - prettier-plugin-java

- name: Has eclint installed
  tags: [system]
  become: true
  community.general.npm:
    global: true
    name: eclint

- name: Has lua server downloaded
  ansible.builtin.get_url:
    url: "https://github.com/LuaLS/lua-language-server/releases/download/3.10.5/lua-language-server-3.10.5-linux-x64.tar.gz"
    dest: "/tmp/lua-lsp.tar.gz"
    mode: "0777"

- name: Has eclipse jdt.ls downloaded
  ansible.builtin.get_url:
    url: "https://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz"
    dest: "/tmp/jdt.tar.gz"

- name: Has pylsp installed
  ansible.builtin.pip:
    name: python-lsp-server

- name: Exist directories for LSPs
  ansible.builtin.file:
    path: "~/Coding/libs/{{ item }}"
    state: directory
  with_items:
    - lua-language-server
    - jdt

- name: Has lua server extracted
  ansible.builtin.unarchive:
    src: "/tmp/lua-lsp.tar.gz"
    dest: "~/Coding/libs/lua-language-server/"

- name: Has eclipse jdt.ls extracted
  ansible.builtin.unarchive:
    src: "/tmp/jdt.tar.gz"
    dest: "~/Coding/libs/jdt/"

- name: Has eclipse jdt.ls configured
  ansible.builtin.shell:
    chdir: "~/Coding/libs/jdt/plugins"
    cmd: "ln -s --force $(ls org.eclipse.equinox.launcher_* | tail -n 1) org.eclipse.equinox.launcher.jar"

- name: Has lombok downloaded
  ansible.builtin.get_url:
    url: "https://projectlombok.org/downloads/lombok.jar"
    dest: "~/Coding/libs/"

- name: Has typescript LSP installed
  tags: [system]
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
  with_items:
    - typescript
    - typescript-language-server

- name: Has vscode LSPs installed (including css)
  tags: [system]
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
  with_items:
    - vscode-langservers-extracted

- name: Has css-modules LSP and stylelint installed
  tags: [system]
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
  with_items:
    - cssmodules-language-server
    - stylelint

- name: Has ansible language server installed
  tags: [system]
  become: true
  community.general.npm:
    name: "@ansible/ansible-language-server"
    global: true

- name: Has ansible-lint installed
  tags: [system]
  become: true
  ansible.builtin.pip:
    name: ansible-lint

- name: Has Lua formatter
  tags: [system]
  community.general.cargo:
    name: "{{ item }}"
  with_items:
    - stylua

- name: Has djlint installed
  tags: [system]
  ansible.builtin.pip:
    name: djlint

- name: Has yaml-language-server installed
  tags: [system]
  community.general.yarn:
    name: yaml-language-server
    global: true

# - name: Has neovim plugins installed
#   command:
#     cmd: "nvim --headless '+Lazy! install' +qa"
