- name: Has neovim-nightly repos
  become: true
  command:
    cmd: dnf copr enable -y agriffis/neovim-nightly

- name: Has pip installed
  become: true
  package:
    name: python3-pip

- name: Has node.js and npm installed
  become: true
  package:
    name: nodejs

- name: Has neovim packages installed
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - neovim
    - glibc-static # needed for treesitter
    - libstdc++-static # needed for treesitter

- name: Has neovim python package installed
  pip:
    name: neovim

- name: Has prettier installed
  become: true
  npm:
    global: yes
    name: "{{ item }}"
  with_items:
    - prettier
    - prettier-plugin-java
    - "@fsouza/prettierd"

- name: Has lua server downloaded
  get_url:
    url: "https://github.com/sumneko/lua-language-server/releases/download/3.2.4/lua-language-server-3.2.4-linux-x64.tar.gz"
    dest: "/tmp/lua-lsp.tar.gz"

- name: Exists directory for lua LSP
  file:
    path: "~/Coding/libs/lua-language-server"
    state: directory

- name: Has lua server extracted
  unarchive:
    src: "/tmp/lua-lsp.tar.gz"
    dest: "~/Coding/libs/lua-language-server/"

# - name: Has neovim plugins installed
#   command:
#     cmd: "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'"
