- name: Has neovim-nightly repos
  become: true
  command:
    cmd: dnf copr enable -y agriffis/neovim-nightly

- name: Has pip installed
  become: true
  package:
    name: python3-pip

- name: Has neovim packages installed
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - neovim
    - glibc-static # needed for treesitter
    - libstdc++-static # needed for treesitter

- name: Has neovim python package installed
  pip:
    name: neovim
