# vi: ft=yaml.ansible

- name: Has rpmfusion repos
  tags: [system]
  become: true
  ansible.builtin.yum:
    disable_gpg_check: true
    name: "{{ item }}"
  loop:
    - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.noarch.rpm
    - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.noarch.rpm
