- name: Create a directory if it does not exist
  file:
    path: "~/.ssh"
    state: directory
    mode: '0755'

- name: Generate SSH key
  openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no
