- name: Has sway-extras Copr repo
  become: true
  command:
    cmd: dnf copr enable -y alebastr/sway-extras

- name: Has sway packages installed
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - sway
    - hyprland
    - rofi
    - xclip
    - light
    - wl-clipboard
    - nwg-launchers
    - nwg-wrapper
    - greetd
    - greetd-gtkgreet
    - swaylock
