# vi: ft=yaml.ansible

- name: Has extra Copr repos
  become: true
  ansible.builtin.command:
    cmd: "dnf copr enable -y {{ item.name }}"
    creates: "{{ item.creates }}"
  with_items:
    - name: alebastr/sway-extras
      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:alebastr:sway-extras.repo
    - name: alternateved/keyd
      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:alternateved:keyd.repo

- name: Has sway packages installed
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - sway
    - rofi
    - xclip
    - light
    - wl-clipboard
    - nwg-launchers
    - nwg-wrapper
    - swaylock
    - wlsunset
    - dunst
    - keyd
