# vi: ft=yaml.ansible

- name: Has extra Copr repos
  become: true
  ansible.builtin.command:
    cmd: "dnf copr enable -y {{ item.name }}"
    creates: "{{ item.creates }}"
  with_items:
    - name: alebastr/sway-extras
      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:alebastr:sway-extras.repo
    - name: alternateved/keyd
      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:alternateved:keyd.repo
    - name: axeld/eww
      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:axeld:eww.repo

- name: Has sway packages installed
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - sway
    - xclip
    - light
    - wl-clipboard
    - nwg-launchers
    - swaylock
    - wlsunset
    - dunst
    - keyd
    - eww

- name: Certain directories exists
  ansible.builtin.file:
    path: /etc/keyd
    state: directory

- name: Has keyd config
  become: true
  ansible.builtin.copy:
    src: ./configs/keyd.conf
    dest: /etc/keyd/default.conf
    mode: '0644'

- name: Has swaycommand script installed
  become: true
  ansible.builtin.copy:
    src: ./configs/swaycommand
    dest: /usr/bin/swaycommand
    mode: '0755'

- name: Has keyd daemon enabled
  become: true
  ansible.builtin.systemd:
    name: keyd
    enabled: true
