- name: Has terminal tools installed
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - foot
    - kitty
    - zsh
    - fzf
    - git
    - feh
    - eza
    - atool
    - unrar
    - ripgrep
    - bat
    - httpie

- name: Find current user
  command: whoami
  register: username

- name: Has zsh as default shell
  become: true
  shell:
    cmd: "usermod --shell /bin/zsh $(whoami)"

- name: Has zplug installed
  command: ls ~/.zplug
  ignore_errors: True
  register: has_zplug

- name: Install zplug
  when: has_zplug is failed
  shell: "curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh"
