# vi: ft=yaml.ansible

- name: Has terminal tools installed
  tags: [system]
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - kitty
    - zsh
    - fzf
    - git
    - feh
    - eza
    - atool
    - unrar
    - ripgrep
    - bat
    - httpie
    - starship

- name: Download font
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/IntelOneMono.zip"
    dest: /usr/share/fonts

- name: Find current user
  ansible.builtin.command: whoami
  register: username

- name: Has zsh as default shell
  become: true
  ansible.builtin.shell:
    cmd: "usermod --shell /bin/zsh $(whoami)"

- name: Has zplug installed
  ansible.builtin.command: ls ~/.zplug
  ignore_errors: true
  register: has_zplug

- name: Install zplug
  when: has_zplug is failed
  ansible.builtin.shell: "curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh"
