Plug 'junegunn/vim-easy-align'
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
Plug 'jiangmiao/auto-pairs'
Plug 'aperezdc/vim-template'
Plug 'skywind3000/asyncrun.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'flazz/vim-colorschemes'
Plug 'vim-scripts/BufOnly.vim'
Plug 'aquach/vim-http-client'
Plug 'junegunn/goyo.vim'
Plug 'ap/vim-buftabline'
Plug 'pearofducks/ansible-vim'
Plug 'junegunn/vim-slash'
Plug 'c0r73x/neotags.nvim'
Plug 'tpope/vim-fugitive'
