Plug 'junegunn/vim-easy-align'
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
Plug 'jiangmiao/auto-pairs'
Plug 'aperezdc/vim-template'
Plug 'skywind3000/asyncrun.vim'
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'airblade/vim-rooter'
Plug 'flazz/vim-colorschemes'
Plug 'vim-scripts/BufOnly.vim'
Plug 'aquach/vim-http-client'
Plug 'junegunn/goyo.vim'
Plug 'taohex/lightline-buffer'
